### ISSUE TITLE
Tracking release 7.0 changes

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/jupyter_client#642]
Since we will be delivering a major release (7.0), I'm hoping we can use this issue to track changes that might affect existing applications.  We should, at this time, go ahead and remove deprecations that have been in place as well as other api-changes (preferably minor in nature). 

- [ ] Remove deprecated [`kernel_cmd`](https://github.com/jupyter/jupyter_client/blob/96e23a843102ccb8e81aa46d1a28d8841804a8f2/jupyter_client/manager.py#L148) trait
- [ ] Remove deprecated [`cleanup()`](https://github.com/jupyter/jupyter_client/blob/96e23a843102ccb8e81aa46d1a28d8841804a8f2/jupyter_client/manager.py#L438) method
- [ ] Remove `block` parameter from [`get_msg()`](https://github.com/jupyter/jupyter_client/blob/96e23a843102ccb8e81aa46d1a28d8841804a8f2/jupyter_client/channels.py#L258)
- [ ] Make kernel manager [`request_shutdown()`](https://github.com/jupyter/jupyter_client/blob/96e23a843102ccb8e81aa46d1a28d8841804a8f2/jupyter_client/manager.py#L381) `async`
- [ ] Rename `KernelSpecManager.whitelist` trait to `allowlist`, `allowed_kernels`, ?
- [ ] Document these changes and others in the docs

We should probably talk about branching as well.  I guess we'll keep working off the tip and create a 6.x branch against the appropriate tag once a 6.x PR is required.

**Comment by kevin-bates** [comment]
Here's an attempt to document the API changes mostly brought about by the Kernel Provisioning changes (#612).  This content will need to be relocated but I wanted to get an initial form persisted somewhere.

## API Changes
All of the API changes for `KernelManager` and `AsyncKernelManager` in the 7.0 release were confined to _internal public_ methods, which we define as methods called from the _formally public_ methods but could be overridden in subclass implementations.  As a result, these changes may impact subclasses of `KernelManager` or `AsyncKernelManager` provided those implementations also implement or call these methods, but should not affect applications that call only the _formally public_ methods.

### `KernelManager`
The following internal methods had signature changes:
- `def pre_start_kernel(self, **kwargs) -> Tuple[List[str], Dict[str, Any]]:`
    - `pre_start_kernel` now returns a tuple consisting of the formatted kernel startup list and an updated set of keyword arguments.
- `def finish_shutdown(self, restart: bool = False):`
    - `finish_shutdown` now takes a keyword argument `restart` indicating the shutdown was on behalf of a restart (when `True`)
- `def _kill_kernel(self, restart: bool = False):`
     - `_kill_kernel` now takes a keyword argument `restart` indicating the termination was on behalf of a restart (when `True`)
- `def _send_kernel_sigterm(self, restart: bool = False):`
     - `_send_kernel_sigterm` now takes a keyword argument `restart` indicating the termination was on behalf of a restart (when `True`)
- `def _launch_kernel(self, kernel_cmd: List[str], **kw) -> None:`
    - `_launch_kernel` now returns `None` instead of the `Popen` instance

- Attribute `kernel` has been removed and _logically_ replaced with `provisioner` - which is an instance of `KernelProvisionerBase` and can be viewed as an abstract `Popen` instance.

### `AsyncKernelManager`
Besides the signature and attribute changes described above, the following internal methods were made `async` for `AsyncKernelManager`:
- `async def pre_start_kernel(self, **kwargs) -> Tuple[List[str], Dict[str, Any]]:`
- `async def post_start_kernel(self, **kwargs)`
- `async def request_shutdown(self, restart: bool = False):`
- `async def cleanup_resources(self, restart: bool = False):`

## Deprecations removed
### Method `KernelManager.cleanup()`
The `cleanup()` method on `KernelManager` has been removed.  `cleanup_resources(restart: bool = False)` should be used.
### Attribute `KernelManager.kernel_cmd`
This attribute had been marked for deprecation for 4 years.  The command used to start the kernel is derived from the `argv` stanza of the kernel specification file (`kernel.json`).

**Comment by blink1073** [comment]
I'm working on the `allowlist` changes, so that leaves documentation as the last item we're tracking.  I'll cut an rc once we get the `allowlist` changes in.

**Comment by blink1073** [comment]
RC coming tomorrow morning US time.

**Comment by blink1073** [comment]
Let's aim for a final release on Mon Aug 16

**Comment by blink1073** [comment]
Let's hold off on the release until #644 is finished

**Comment by blink1073** [comment]
Looks like we're good!  I'll handle the changelog and cut the release after getting lunch.
